# AcidRain config file

# Time between in seconds
check-interval: 10

# Damage per interval
damage-per: 1

# How many half-hearts to stop damage at.
damage-cutoff: 0

# Leather armor will act like a raincoat
leather-raincoat: true

# Rain can be poisonous
poisonrain: false

# Chance to poison a player
poisonchance: 10

# Output Verbose messages?
verbose: false