# AcidRain config file

# Time between in seconds
check-interval: 10

# Damage per interval
damage-per: 1

# How many half-hearts to stop damage at.
damage-cutoff: 0

# Leather armor will act like a raincoat
leather-raincoat: true

# Rain can be poisonous
poison-rain: false

# Chance to poison a player (0 - 100)
poison-chance: 10

# Duration of poison effect in seconds
poison-duration: 5

# Output Verbose messages?
verbose: false