name: AcidRain
main: com.nuclearw.acidrain.AcidRain
version: ${project.version}
authors: [NuclearW, jkcclemens, Tunix2, SonarBeserk]
description: AcidRain makes rain dangerous.
permissions:
  acidrain.immune:
    description: Protects players from acid rain damage.
    default: false