name: AcidRain
main: com.nuclearw.acidrain.AcidRain
version: ${project.version}
authors: [NuclearW, jkcclemens, Tunix2, SonarBeserk]
description: AcidRain makes rain dangerous.
permissions:
  acidrain.immune:
    description: Protects players from acid rain damage.
    default: false
  acidrain.reload:
    description: Allows Reloading of the Config
    default: op 
commands:
  acidrain:
    description: Base Command for acidrain
    aliases: [ar]
    usage: "Usage: /<command> (subcommand) [args]"     